# Generated by Django 4.2.11 on 2024-05-19 09:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_transaction_created_on_transaction_updated_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='vocabulary',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='vocabulary-images'),
        ),
        migrations.CreateModel(
            name='UserVocabulary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('running', 'Running'), ('completed', 'Completed')], default='running', max_length=20)),
                ('vocabulary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.vocabulary')),
            ],
        ),
    ]
