# Generated by Django 4.2.11 on 2024-05-19 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_vocabulary_image_uservocabulary'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserVocabulary',
        ),
    ]
