# Generated by Django 4.2.11 on 2024-05-19 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_uservocabulary'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vocabulary',
            name='video_url',
        ),
        migrations.AddField(
            model_name='vocabulary',
            name='video_file',
            field=models.FileField(blank=True, null=True, upload_to='video-files'),
        ),
    ]
