# Generated by Django 4.2.11 on 2024-07-21 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_userprofile_subscribed_alter_userprofile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='level',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
